crashfix_webapp/protected/controllers/ProjectController.php
<?php

class ProjectController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	public $sidebarActiveItem = 'Administer';
	public $adminMenuItem='Projects';
	
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view', 'create','update', 'addUser', 'deleteUser', 'disable', 'enable', 'delete'),
				'roles'=>array('gperm_access_admin_panel'),
			),			
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$model = $this->loadModel($id);
		
		$this->render('view',array(
			'model'=>$model,
			'dataProvider'=>$model->searchUsers()
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Project;
		
		if(isset($_POST['Project']))
		{
			$model->attributes=$_POST['Project'];
			if($model->save())
            {
                Yii::app()->user->setFlash(
                            'success', 
                            'Project '.$model->name.' has been created successfully.'
                            );     
                
				$this->redirect(array('view','id'=>$model->id));
            }
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Project']))
		{
			$model->attributes=$_POST['Project'];
			if($model->save())
            {
                Yii::app()->user->setFlash(
                            'success', 
                            'Project information has been updated.'
                            );                
                
				$this->redirect(array('view','id'=>$model->id));
            }
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Disables the project.
	 */
	public function actionDisable()
	{
		if(Yii::app()->request->isPostRequest)
		{
			if(!isset($_POST['id']))
				throw new CHttpException(403, 'Invalid request');
			
			$id = $_POST['id'];
			
			// we only allow this via POST request
			$this->loadModel($id)->enable(false);

			
			$this->redirect(array('view', 'id'=>$id));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}
	
	/**
	 * Enables the project.
	 */
	public function actionEnable()
	{
		// We only allow this via POST request
		if(Yii::app()->request->isPostRequest)
		{
			if(!isset($_POST['id']))
				throw new CHttpException(403, 'Invalid request');
			
			$id = $_POST['id'];
									
			$this->loadModel($id)->enable(true);

			
			$this->redirect(array('view', 'id'=>$id));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}
	
	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 */
	public function actionDelete()
	{
		if(Yii::app()->request->isPostRequest)
		{
			if(!isset($_POST['id']))
				throw new CHttpException(403, 'Invalid request');
			
			$id = $_POST['id'];
			
			$model = $this->loadModel($id);
			
			// we only allow this via POST request
			if($model->delete())
			{
				Yii::app()->user->setFlash('success', 
						'The project '.$model->name.' has been deleted.');
			}
			else
			{
				Yii::app()->user->setFlash('error', 
						'The project '.$model->name.' could not be deleted.');
			}
			
			$this->redirect(array('index'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Adds a user to project.
	 */
	public function actionAddUser()
	{		
		if(!isset($_POST['id']))
            throw new CHttpException(403, 'Invalid request');
		
        $projectId = $_POST['id'];
        
        $project = Project::model()->findByPk($projectId);
        if($project===Null)
            throw new CHttpException(403, 'Invalid request');
        
		if(isset($_POST['User']))
		{   
            // Get items
            $items = $_POST['User'];
            
            // Get values of checkbox column
            $checks = array();
            if(isset($_POST['check']))
                $checks = $_POST['check'];
            
            // Walk through items
            foreach($items as $userId=>$item)
            {
                // Find user project access record 
                $model = UserProjectAccess::model()->findByAttributes(
                        array('user_id'=>$userId,
                            'project_id'=>$projectId));
                
                // Find out if this item is checked or not
                if(in_array($userId, $checks)) // checked
                {
                    if($model===Null) // If this user has no access to this project...
                    {
                        // Give him access
                        $model = new UserProjectAccess();
                        $model->user_id = $userId;
                        $model->project_id = $projectId;
                        $model->usergroup_id = $item['usergroup'];

                        if(!$model->save())
                            throw new CHttpException(403, 'Error saving record to database');				                
                    }
                }
                else // unchecked
                {
                    if($model!=Null) // If user has access to project
                    {
                        // Revoke access
                        if(!$model->delete())
                            throw new CHttpException(403, 'Error deleting record from database');				                
                    }
                }
			}
            
            Yii::app()->user->setFlash(
                            'success', 
                            'User roles have been updated.'
                            );
                    
            $this->redirect(array('project/view', 'id'=>$projectId));					
            return;
		}
        
        $criteria=new CDbCriteria;                

        $dataProvider =  new CActiveDataProvider('User', array(
            'criteria'=>$criteria,
            'sort'=>array(
                'defaultOrder'=>'username ASC'
            ),
            'pagination'=>false
        ));

        
        $this->render('addUser',array(
            'project'=>$project,
            'dataProvider'=>$dataProvider
        ));        
	}
	
	/**
	 * Removes one or several users from project.
	 */
	public function actionDeleteUser()
	{		
		if(!isset($_POST['DeleteRows']) || !isset($_POST['project_id']))
		{
			throw new CHttpException(404, 'The parameter is invalid');
		}
				
		// Get data from user
		$deleteRows=$_POST['DeleteRows'];
		$projectId = $_POST['project_id'];
		
		foreach($deleteRows as $id)
		{
			$model = UserProjectAccess::model()->findByPk($id);
			if($model===Null)
				throw new CHttpException(404, 'The specified record doesn\'t exist in the database.');
				
			// Delete row from database table 
			if(!$model->delete())
			{
				throw new CHttpException(404, 'The specified record doesn\'t exist in the database or could not be deleted.');
			}
		}
        
        Yii::app()->user->setFlash(
            'success', 
            'User roles have been updated.'
            );
		
		// Redirect to index
		$this->redirect(array('project/view', 'id'=>$projectId));
	}	
	
	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Project');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Project('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Project']))
			$model->attributes=$_GET['Project'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Project::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='project-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

crashfix_webapp/protected/views/project/_form.php
<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'project-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="subheader">General Info:</div>
	
	<div class="row idented">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>32,'maxlength'=>32)); ?>
		<?php echo $form->error($model,'name'); ?>
	</div>
	
	<div class="row idented">
		<?php echo $form->labelEx($model, 'description'); ?>
		<?php echo $form->textField($model,'description',array('size'=>60,'maxlength'=>128)); ?>
		<?php echo $form->error($model,'description'); ?>
	</div>
	
	<div class="subheader">Project Quotas:</div>

	<div class="row idented">
		<?php echo $form->labelEx($model, 'crash_reports_per_group_quota'); ?>
		<?php echo $form->textField($model,'crash_reports_per_group_quota',array('size'=>10,'maxlength'=>10)); ?>
		<?php echo $form->error($model,'crash_reports_per_group_quota'); ?>
	</div>
	
	<div class="row idented">
		<?php echo $form->labelEx($model, 'crash_report_files_disc_quota'); ?>
		<?php echo $form->textField($model,'crash_report_files_disc_quota',array('size'=>32,'maxlength'=>32)); ?>
		<?php echo $form->error($model,'crash_report_files_disc_quota'); ?>		
	</div>
        
        <div class="row idented">
		<?php echo $form->labelEx($model, 'bug_attachment_files_disc_quota'); ?>
		<?php echo $form->textField($model,'bug_attachment_files_disc_quota', array('size'=>32, 'maxlength'=>32)); ?>
		<?php echo $form->error($model,'bug_attachment_files_disc_quota'); ?>		
	</div>
	
	<div class="row idented">
		<?php echo $form->labelEx($model, 'debug_info_files_disc_quota'); ?>
		<?php echo $form->textField($model,'debug_info_files_disc_quota',array('size'=>32,'maxlength'=>32)); ?>
		<?php echo $form->error($model,'debug_info_files_disc_quota'); ?>		
	</div>

	<div class="subheader">Misc Options:</div>
    
    <div class="row idented">
		<?php echo $form->labelEx($model, 'require_exact_build_age'); ?>
		<?php echo $form->checkBox($model,'require_exact_build_age'); ?>
		<?php echo $form->error($model,'require_exact_build_age'); ?>		
	</div>
	
	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

crashfix_webapp/protected/views/project/_search.php
<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>128)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

crashfix_webapp/protected/views/project/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />


</div>

crashfix_webapp/protected/views/project/addUser.php
<?php
$this->breadcrumbs=array(
	'Administer', 
	'Projects'=>array('project/index'),
	CHtml::encode($project->name),
	'Add Project Members'
);

?>

<div class="span-18 last">

    <div class="form">
    
        <div class="hint">
                Check the boxes next to the names of projects in which the user must 
                participate, and then click the Save button to apply your changes.
        </div>

        <?php $form=$this->beginWidget('CActiveForm', array(
            'id'=>'add-project-role-form',
            'enableAjaxValidation'=>false,
        )); ?>

        <?php echo CHtml::hiddenField('id', $project->id); ?>

        <!-- Grid view -->
        <div class="span-18 last">
        <?php     

            $models = UserGroup::model()->findAll(); 
            $list = CHtml::listData($models, 'id', 'name');

            $this->widget('zii.widgets.grid.CGridView', array(
            'dataProvider'=>$dataProvider,
            'selectableRows'=>null,
            'summaryText'=>'',
            'columns'=>array(		            
                array(                          
                    'class'=>'CCheckBoxColumn',			  			  
                    'id'=>'check',
                    'selectableRows'=>2, // allow multiple rows to select                            
                    'checked'=> function($data,$row) use ($project) {return $data->isInProject($project->id);}
                ),
                array(     
                    'header'=>'User Name',
                    'name'=>'username',
                    'type' => 'raw',			  
                    'value' =>'CHtml::link($data->username, array(\'user/view\', \'id\'=>$data->id))',	  			  			  
                ),	
                array(     
                    'name'=>'usergroup',
                    'header'=>'Role',
                    'type'=>'raw',
                    'id'=>'User[][usergroup]',
                    'value'=>function($data,$row) use ($list, $project){ return CHtml::dropDownList("User[".$data->id."][usergroup]", array('selected'=>$data->suggestProjectRole($project->id)), $list); },              
                    ),
            ),
        )); 
        ?>

        <?php echo CHtml::submitButton('Save', array('id'=>'add_role')); ?>

        <?php $this->endWidget(); ?>

        </div>
        
    </div>
</div>

crashfix_webapp/protected/views/project/create.php
<?php
$this->breadcrumbs=array(
	'Projects'=>array('index'),
	'Add New Project',
);

$this->menu=array(
	array('label'=>'List Project', 'url'=>array('index')),
	array('label'=>'Manage Project', 'url'=>array('admin')),
);
?>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

crashfix_webapp/protected/views/project/index.php
<?php
$this->pageTitle=Yii::app()->name . ' - Manage Projects';
$this->breadcrumbs=array(	
	'Administer', 
	'Projects',
);

?>

<!-- Flash messages -->
<div class="span-18 last">
<?php	
    foreach(Yii::app()->user->getFlashes() as $key => $message) {
        echo '<div class="flash-' . $key . '">' . $message . "</div>\n";
    }
?>
</div>

<!-- Actions Toolbar -->
<div class="span-18 last">
	<div class="div_actions">
		<?php echo CHtml::link('Add New Project', $this->createUrl('project/create')); ?>		
	</div>	
</div>

<!-- Grid view -->
<div class="span-18 last">
<?php $this->widget('zii.widgets.grid.CGridView', array(
      'dataProvider'=>$dataProvider,
	  'selectableRows'=>null,
      'columns'=>array(		  
          'id',                       
		  array(            
              'name' => 'name',
			  'type' => 'raw',
			  'value' => 'CHtml::link($data->name, \'view/\'.$data->id)',	  			  			  
          ),
		  array(                          			  
			  'name'=>'status',
			  'type' => 'text',
			  'value'=>'Lookup::item(\'ProjectStatus\', $data->status)',			  
          ),
		  'description',  
		  
      ),
 )); 
  
 ?>
</div>

crashfix_webapp/protected/views/project/update.php
<?php
$this->breadcrumbs=array(
	'Administer',
	'Projects'=>array('index'),
	$model->name=>array('view','id'=>$model->id),
	'Update',
);

?>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

crashfix_webapp/protected/views/project/view.php
<?php
$this->breadcrumbs=array(
	'Administer', 
	'Projects'=>array('index'),
	$model->name,
);

?>

<!-- Flash messages -->
<div class="span-18 last">
<?php
foreach (Yii::app()->user->getFlashes() as $key => $message) {
    echo '<div class="flash-' . $key . '">' . $message . "</div>\n";
}
?>
</div>

<!-- Actions Toolbar -->
<div class="span-18 last">
	<div class="div_actions">
		
			<?php echo CHtml::form(); ?>		
		
			<?php echo CHtml::hiddenField('id', $model->id); ?>			
		
			<?php
				
				echo CHtml::linkButton('Update Project', 
							array('submit'=>Yii::app()->createUrl('project/update', array('id'=>$model->id)))
							);			
				
				if($model->status==Project::STATUS_ACTIVE)
				{
					echo CHtml::linkButton('Disable Project', 
							array('submit'=>Yii::app()->createUrl('project/disable'))
							);			
				}
				else
				{
					echo CHtml::linkButton('Enable Project', 
							array('submit'=>Yii::app()->createUrl('project/enable'))
							);			
				}
				
				echo CHtml::linkButton('Delete Project', 
							array('submit'=>Yii::app()->createUrl('project/delete'),
								'confirm'=>"Are you sure you want to permanently delete this project?")						
							);			
			?>	
		
			<?php echo CHtml::endForm(); ?>		
	</div>	
</div>

<div class="span-18 last">
<div class="subheader">Project Info:</div>

<!-- Detail View -->
<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(		
		'name',
		'description',
		array(  
            'name'=>'status',
            'type'=>'text',
            'value'=>Lookup::item('ProjectStatus', $model->status),		
        ),		
	),
)); ?>
</div>

<div class="span-18 last">
<div class="subheader">Project Quotas:</div>

<!-- Detail View -->
<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(				
		'crash_reports_per_group_quota',
		'crash_report_files_disc_quota',
		'bug_attachment_files_disc_quota',
		'debug_info_files_disc_quota'
	),
)); ?>
</div>

<div class="span-18 last">
<div class="subheader">Misc Options:</div>

<!-- Detail View -->
<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(	
        array(  
            'name'=>'require_exact_build_age',		
            'type'=>'text',
            'value'=>$model->require_exact_build_age!=0?'Yes (recommended)':'No'),		
        ),		
	)
); ?>
</div>

<!-- Actions Toolbar -->
<div class="span-18 last">
<p></p>

<h4>Users Participating in this Project:</h4>

    <div class="div_actions">
		
			<?php echo CHtml::form(); ?>		
		
			<?php echo CHtml::hiddenField('id', $model->id); ?>			
		
			<?php
			
                echo CHtml::linkButton('Add User(s)', 
                            array('submit'=>Yii::app()->createUrl('project/addUser'))
                            );			
								
				echo CHtml::link("Remove Selected Users", "#", array('id'=>'delete_selected'));
			?>	
		
			<?php echo CHtml::endForm(); ?>		
	</div>	
</div>

<?php echo CHtml::beginForm(array('project/deleteUser'), 'post', array('name'=>'del_form')); ?>

<?php echo CHtml::hiddenField('project_id', $model->id); ?>

<!-- Grid view -->
<div class="span-18 last">
<?php $this->widget('zii.widgets.grid.CGridView', array(
      'dataProvider'=>$dataProvider,
	  'selectableRows'=>null,
      'columns'=>array(		            
		  array(                          
              'class'=>'CCheckBoxColumn',			  			  
			  'id'=>'DeleteRows',
			  'selectableRows'=>2, // allow multiple rows to select
          ),
		  array(     
			  'name'=>'user_id',
			  'type' => 'raw',			  
			  'value' => 'CHtml::link($data->user->username, array(\'user/view\', \'id\'=>$data->user_id))',	  			  			  
          ),	
		  array(     
			  'name'=>'usergroup_id',
			  'type' => 'raw',			  
			  'value' => 'CHtml::link($data->usergroup->name, array(\'userGroup/view\', \'id\'=>$data->usergroup_id))',	  			  			  
          ),
      ),
 )); 
  
 ?>

</div>

<?php echo CHtml::endForm(); ?>

<?php 
 $script = <<<SCRIPT
$(":checkbox").live('click', function(e)
{		
	var totalSelected = 0;
	$("input[name='DeleteRows\[\]']").each(function() {if($(this).attr('checked')) totalSelected++;});
	
	if(totalSelected==0)
		$("#delete_selected").css('visibility', 'hidden');
	else
		$("#delete_selected").css('visibility', 'visible');
	
});

$("#delete_selected").bind('click', function(e)
{	
	$("[name=del_form]").submit();
});

SCRIPT;
 
 Yii::app()->getClientScript()->registerScript("DebugInfo", $script, CClientScript::POS_READY); ?>