crashfix_webapp/protected/models/Bug.php
<?php

// The following is needed to use ezComponents Graph
Yii::import('application.vendors.ezcomponents.*');
require_once "Base/src/base.php"; 
Yii::registerAutoloader(array('ezcBase', 'autoload'), true);

/**
 * This is the model class for table "{{bug}}".
 */
class Bug extends CActiveRecord
{	
	// Open statuses.
	const STATUS_NEW      = 1;   // New bug.
	const STATUS_REVIEWED = 2;   // Bug is being reviewed.
	const STATUS_ACCEPTED = 3;   // Bug accepted.
	const STATUS_STARTED  = 4;   // Bug is being fixed.	
	const STATUS_OPEN_MAX = 100; // Maximum available open status.
	// Closed statuses.
	const STATUS_FIXED     = 101; // Bug has been fixed.
	const STATUS_VERIFIED  = 102; // Bug has been verified by QA
	const STATUS_DUPLICATE = 103; // Bug is a duplicate of another bug
	const STATUS_WONTFIX   = 104; // We have decided not to take an action on this bug.
	
	// Bug priorities
	const PRIORITY_LOW      = 1; // Low priority
	const PRIORITY_MEDIUM   = 2; // Medium priority
	const PRIORITY_HIGH     = 3; // High priority
	const PRIORITY_CRITICAL = 4; // Critical priority
	
	// Bug reproducibility constants
	const REPRO_NOT_TRIED   = 1; // Not tried to reproduce this bug.
	const REPRO_NEVER       = 2; // Bug can never be reproduced.  
	const REPRO_SOMETIMES   = 3; // Bug can be sometimes reproduced.
	const REPRO_ALWAYS      = 4; // Bug can always be reproduced.
	
	// Non-db attributes
	public $crashreports;   // Space-separated list of crash reports associated with this bug.
	public $crashgroups;    // Space-separated list of crash groups associated with this bug.	
	public $comment;        // Comment (used on change).
	public $fileAttachment; // File attachment (used on change).	
	public $cnt; // Count (used in stat query)
    
	// Search related variables
	public $filter; // Simple search filter.
	public $bugStatusFilter; // Simple search bug status filter;
	public $isAdvancedSearch = false; // Is advanced search enabled?
	public $createdFrom; // Received from (used in advanced search).
	public $createdTo;   // Received to (used in advanced search).
    	
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Bug the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{bug}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('summary, assigned_to', 'required', 'on'=>'create, change'), // Summary required always
			array('status, priority, reproducability, description, assigned_to', 'required', 'on'=>'create'),
			array('status, priority, reproducability, assigned_to', 'numerical', 'integerOnly'=>true),
			array('summary', 'length', 'min'=>1, 'max'=>256),			
			array('description', 'length', 'min'=>1, 'max'=>2048),					
			array('crashgroups', 'numberList', 'CrashGroup'),
			array('crashreports', 'numberList', 'CrashReport'),
			array('crashgroups', 'atLeastRequired', 'crashgroups, crashreports', 'count'=>1, 'on'=>'create, change'),
			// The following rules are used on change
			array('fileAttachment', 'file', 'maxFiles'=>1, 'minSize'=>1, 'maxSize'=>20*1024*1024, 'allowEmpty'=>true, 'on'=>'change'),
			array('comment', 'length', 'max'=>2048, 'on'=>'change'),					
			array('reporter, description', 'unsafe', 'on'=>'change'),								
			array('merged_into', 'checkMergedInto', 'on'=>'change'),								
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, date_created, status, priority, summary, reported_by, assigned_to', 'safe', 'on'=>'search'),
			array('createdFrom', 'compareDates', 'on'=>'search'),
		);
	}

	/**
	 * This validator method checks 'merged_into' attribute.
	 * @param string $attribute Attribute name.
	 * @param array $params Parameters.
	 * @return boolean true on success.
	 */
	public function checkMergedInto($attribute, $params)
	{
		if($this->status==self::STATUS_DUPLICATE)
		{
			if(isset($this->merged_into) &&
				is_numeric($this->merged_into))
			{
				// Search for a bug with such an ID.
				$bug = Bug::findByPk($this->merged_into);
				if($bug!=null && $bug->id!=$this->id && $bug->project_id==$this->project_id)
					return true; // OK.
			}
			
			// Not a valid bug ID.
			$this->addError('merged_into', 'Merged Into should be a valid bug ID.');
			return false;
		}
		else
		{
			// Unset to avoid errors
			unset($this->merged_into);
		}
		
		// OK.
		return true;
	}
	
	/**
	 * This validator checks if at least one attribute is defined.
	 * @param string $attribute Attribute name.
	 * @param array $params Parameters.
	 * @return boolean  true on success.
	 */
	public function atLeastRequired($attribute, $params) 
	{		
		if (is_array($params)) 
		{
			$fields = explode(', ', $params[0]);
			$min = $params['count'];
		} 
		/*else 
		{
			$fields = explode(', ', $params);
			$min = 1;
		}*/
		$count = 0;
		$labels = array();
		foreach ($fields as $name) 
		{
			$labels[] = $this->getAttributeLabel($name);
			if ( !empty($this->$name) ) { $count++; }							
		}		
		if ($count < $min) 
		{
			$this->addError($attribute, 'At least one of these required: '.implode(', ', $labels) );
			return false;
		}
		
		return true;
	}
	
	/**
	 * This validator method checks if the attribute is a list of space separated
	 * numbers.
	 * @param string $attribute Attribute name.
	 * @param array $params Parameters.
	 * @return boolean true on success.
	 */
	public function numberList($attribute,$params)
    {
		if($this->scenario=='search')
			return true; // Do not check on search.
			
		if(!isset($this->$attribute) || strlen(trim($this->$attribute))==0)
			return true; // Empty
		
		$numbers = MiscHelpers::splitNumberList($this->$attribute);
		if($numbers==false)
		{
			$this->addError($attribute, $this->getAttributeLabel($attribute).' must be a list of numbers separated with spaces.');
			return false;
		}
				
		$appversion = 0;
		foreach($numbers as $number)
		{	
			// Check if such a crash report/crash group exists
			$model = $params[0]::model()->findByPk($number);
			if($model===null || !$model->canOpenNewBug())
			{
				$this->addError($attribute, $this->getAttributeLabel($attribute).' must contain valid ID(s).');
				return false;
			}		
									
		}
		        
		return true;
    }
	
	/**
	 *  This validator compares Date From and Date To to ensure Date To is the greater one.
	 * @param string $attribute Attribute name.
	 * @param array $params Parameters.
	 * @return boolean true on success.
	 */
	public function compareDates($attribute, $params)
	{
		// Check scenarion
		if($this->scenario!='search')
			return true;
		
		// Check if both dates are set
		if(!isset($this->createdFrom) || !isset($this->createdTo))
			return true;
		
		// Convert date strings to timestamps
		$date1 = $this->strToDate($this->createdFrom);
		$date2 = $this->strToDate($this->createdTo);
		
		// Check timestamps
		if($date1==False || $date2==False)
			return true; // One of dates is invalid - nothing to compare
		
		// Compare dates
		if($date2>=$date1)
			return true; // Date To is greater than Date From
		
		// Error
		$this->addError('createdTo', 'Created To must be greater or equal to Created From.');
		return false;		
	}
	
	/**
	 * A helper method that converts a date string to timestamp.
	 * @param string $date Date string
	 * @return integer timestamp.
	 */
	public function strToDate($date)
	{
		$timestamp=CDateTimeParser::parse($date,'MM/dd/yyyy');
		return $timestamp;
	}
	
	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'reporter'=>array(self::BELONGS_TO, 'User', 'reported_by'),
			'owner'=>array(self::BELONGS_TO, 'User', 'assigned_to'),
			'crashReports'=>array(self::HAS_MANY, 'BugCrashReportMapping', 'bug_id'),
			'crashGroups'=>array(self::HAS_MANY, 'BugCrashGroupMapping', 'bug_id'),
			'bugchanges'=>array(self::HAS_MANY, 'BugChange', 'bug_id'),
			'project'=>array(self::BELONGS_TO, 'Project', 'project_id'),
            'appVersion'=>array(self::BELONGS_TO, 'AppVersion', 'appversion_id'),			
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'date_created' => 'Created',
			'status' => 'Status',
			'summary' => 'Summary',
			'assigned_to' => 'Owner',
			'reported_by' => 'Reporter',
			'crashreports' => 'Crash reports associated with this bug',
			'crashgroups' => 'Collections associated with this bug',
            'reproducability' => 'Reproducibility'
		);
	}

	/**
	 * Fills summary and description field based on associated crash group
	 * or crash report information.
	 * @return void
	 * @throws CHttpException 
	 */
	public function autoFillSummary()
	{
		if(isset($this->crashgroups))
		{
			if(!is_numeric($this->crashgroups))
				throw new CHttpException(403, 'Invalid request.');
		
			$crashGroupId = $this->crashgroups;
			$crashGroup = CrashGroup::model()->findByPk($crashGroupId);
			if($crashGroup===null)
				throw new CHttpException(403, 'Invalid request.');

			$this->summary = $crashGroup->title;
			$this->description = 'Bug on Collection #'.$crashGroup->id;
		}
		else if(isset($this->crashreports))
		{
			if(!is_numeric($this->crashreports))
				throw new CHttpException(403, 'Invalid request.');
			
			$crashReportId = $this->crashreports;
			$crashReport = CrashReport::model()->find($crashReportId);
			if($crashReport===null)
				throw new CHttpException(403, 'Invalid request.');

			$this->summary = 'Bug on Crash Report #'.$crashReport->id;

crashfix_webapp/protected/controllers/BugController.php
<?php

// The following is needed to use ezComponents Graph
Yii::import('application.vendors.ezcomponents.*');
require_once "Base/src/base.php"; 
Yii::registerAutoloader(array('ezcBase', 'autoload'), true);

class BugController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';
	
	/**
	 * @var string the active item for sidebar menu.
	 */
	public $sidebarActiveItem = 'Bugs';
	
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  
				'actions'=>array(
					'index', 
					'view', 
					'downloadAttachment', 
					'statusDynamics',
                    'statusDist',
					'create', 
					'delete', 
					'deleteMultiple'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}
	
	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		// Load bug with such an ID
		$model = $this->loadModel($id);
		
		// Check that user is authorized to access this model
		$this->checkAuthorization($model);
		
		if(isset($_POST['Bug']))
		{		
			// Get file attachment            
			$model->fileAttachment = CUploadedFile::getInstance($model, 'fileAttachment');
			
			// Apply the change to bug
			$model->change($_POST['Bug']);			
		}
				
		// Render view
		$this->render('view',array(
			'model'=>$model,
		));
	}
		
	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		// Check that user is authorized to create new bugs
		$this->checkAuthorization(null);
		
		// Create new model
		$model=new Bug;
		
		if(isset($_GET['crashgroup']))
		{		
			// The bug is being created for a particular crash group.
			$model->crashgroups = $_GET['crashgroup'];
			// Automatically fill the summary and description fields
			$model->autoFillSummary();
		}
		
		if(isset($_GET['crashreport']))
		{
			// The bug is being created for a particular crash report.
			$model->crashreports = $_GET['crashreport'];	
			// Automatically fill the summary and description fields
			$model->autoFillSummary();
		}
		
		// Fill model fields
		if(isset($_POST['Bug']))
		{
			$model->attributes=$_POST['Bug'];
			if($model->open())
			{				
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		// Render view
		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.	 
	 */
	public function actionDelete()
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			if(!isset($_POST['id']))
				throw new CHttpException(400, 'Invalid request');
			
			$id = $_POST['id'];
			
			$model = $this->loadModel($id);
			
			// Check that user is authorized to access this model
			$this->checkAuthorization($model);
			
			// Delete model
			$model->delete();			
			
			// Redirect to index
			$this->redirect('index');
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		// Check that user is authorized to perform this action
		$this->checkAuthorization(null);
		
		$model = new Bug('search');
		if(isset($_GET['q']))
		{
			$model->filter = $_GET['q'];
			if(isset($_GET['status']))
				$model->bugStatusFilter = $_GET['status'];
		}
		else if(isset($_POST['Bug']))
		{			
			// Advanced search	
			$model->isAdvancedSearch = true;			
			
			// Fill form with data
			$model->attributes = $_POST['Bug'];			
		}
		
		$dataProvider=$model->search();
		
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
			'model'=>$model
		));
	}

	/**
	 * Downloads a bug attachment file.
	 * @param type $id
	 * @throws CHttpException 
	 */
	public function actionDownloadAttachment($id)
	{
		$bugAttachment = BugAttachment::model()->findByPk($id);
		if($bugAttachment===null)
			throw new CHttpException(403, 'Invalid request');
		
		// Get the bug this attachment belongs to
		$bug = $bugAttachment->bugChange->bug;
		
		// Check that user is authorized to access this model
		$this->checkAuthorization($bug);
		
		// Dump contents of the attachment
		$bugAttachment->dumpFileAttachmentContent();		
	}
	
	
	/**
	 * This action generates an image with bug status statistics
	 * for the current project/version. 
	 * @param integer $w Image width.
	 * @param integer $h Image height.
	 * @param integer $period Time period (7, 30 or 365).
	 */
	public function actionStatusDynamics($w, $h, $period)
	{	
		// Check that user is authorized to view statistics of this project
		$this->checkAuthorization(null);
		
		Bug::generateBugStatusDynamicsGraph($w, $h, $period);
	}
    
    /**
	 * This action generates an image with bug status distribution
	 * for the current project/version. 
	 * @param integer $w Image width.
	 * @param integer $h Image height.	 
	 */
	public function actionStatusDist($w, $h)
	{	
		// Check that user is authorized to view statistics of this project
		$this->checkAuthorization(null);
		
		Bug::generateBugStatusDistributionGraph($w, $h);
	}
	
	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Bug::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}	
	
	
	/**
	 * Checks if user is authorized to perform the action.
	 * @param Bug $model Authorization object. Can be null.
	 * @param string $permission Permission name.
	 * @throws CHttpException
	 * @return void
	 */
	protected function checkAuthorization($model, $permission = 'pperm_browse_bugs')
	{		
		if($model==null)
		{
			$projectId = Yii::app()->user->getCurProjectId();
			if($projectId==false)
				return;
		}
		else
			$projectId = $model->project_id;	
		
		// Check if user can perform this action
		if(!Yii::app()->user->checkAccess($permission, 
				array('project_id'=>$projectId)) )
		{
			throw new CHttpException(403, 'You are not authorized to perform this action.');
		}
	}
}

crashfix_webapp/protected/views/bug/_bugChange.php
<div class="bug-change">
	
	<div class="bug-change-header">
		Change #<?php echo $changeNum ?> 
		by <?php echo CHtml::encode($model->user->username) ?> 
		on <?php echo date('j F Y, G:i', $model->timestamp) ?>
	</div>
	
	<?php 
		if($model->comment!=null)
		{				
			echo '<div class="bug-change-comment">'.CHtml::encode(str_replace("<br>", "\n", $model->comment->text)).'</div>';  				
		}		

		if($model->statuschange)
		{
			echo '<div class="bug-change-status"><ul>';

			if(isset($model->statuschange->status))
				echo '<li>Status: '.Lookup::item('BugStatus', $model->statuschange->status);
			if(isset($model->statuschange->merged_into))
				echo '<li>Merged into bug: '.CHtml::link($model->statuschange->merged_into, array('bug/view', 'id'=>$model->statuschange->merged_into));
			if(isset($model->statuschange->priority))
				echo '<li>Priority: '.Lookup::item('BugPriority', $model->statuschange->priority);
			if(isset($model->statuschange->reproducability))
				echo '<li>Reproducibility: '.Lookup::item('BugReproducability', $model->statuschange->reproducability);
			
            if(isset($model->statuschange->assigned_to))				
            {
                if($model->statuschange->assigned_to>=0)
                    echo '<li>Owner: '.(isset($model->statuschange->owner)?CHtml::encode($model->statuschange->owner->username):'user was deleted');
                else
                    echo '<li>Owner: nobody';
            }            
                
            echo '</ul></div>';
		}

		foreach($model->attachments as $attachment)
		{				
			echo '<div class="bug-change-attach">'.CHtml::image(Yii::app()->baseUrl.'/images/file.png').
				'File attached: '.						
					CHtml::link(CHtml::encode($attachment->filename), 
							array('bug/downloadAttachment', 'id'=>$attachment->id)).
				' ('.MiscHelpers::fileSizeToStr($attachment->filesize).')'.
				'</div>';
		}
	?>
		
	
</div>

crashfix_webapp/protected/views/bug/index.php
<?php
$this->pageTitle=Yii::app()->name . ' - Browse Bugs';
$this->breadcrumbs = array(
    'Bugs',
);
?>

<?php if (count(Yii::app()->user->getMyProjects()) == 0): ?>

    You have no projects assigned.

<?php else: ?>

    <!-- Project Selection Form -->
    <div class="span-27 last" id="div_proj_selection">	
        <?php echo CHtml::beginForm(array('site/setCurProject'), 'get', array('id' => 'proj_form')); ?>
        <div class="span-27 last">
            Current Project:
            <?php
                $models = Yii::app()->user->getMyProjects();
                $projects = CHtml::listData($models, 'id', 'name');
                echo CHtml::dropDownList('proj', array('selected' => Yii::app()->user->getCurProjectId()), $projects);
            ?>					
            Version:
            <?php
                $selVer = -1;
                $versions = Yii::app()->user->getCurProjectVersions($selVer);
                echo CHtml::dropDownList('ver', array('selected' => $selVer), $versions);
            ?>					
        </div>
        <?php echo CHtml::endForm(); ?>
    </div>

    <!-- Simple Search Form -->
    <div class="span-27 last" id="div_simple_search" style="display:<?php echo!$model->isAdvancedSearch ? 'inherit' : 'none' ?>">	
        <?php echo CHtml::beginForm('index', 'get', array('id' => 'proj_form')); ?>
        <div class="span-27 last"><p id="stat_filter">Search by Symmary/Reporter/Owner or use <a href="#" id="link_advanced_search">advanced search</a>:</p></div>
        <div class="span-6">
            <div id="dropdown_search">
                <?php
                $bug_statuses = array(
                    'all' => 'All bugs',
                    'open' => 'Open bugs',
                    'owned' => 'Open and owned by me',
                    'reported' => 'Open and reported by me',
                    'verify' => 'Bugs to verify',
                    'closed' => 'Closed bugs',
                );
                echo CHtml::dropDownList('status', array('selected' => isset($model->bugStatusFilter) ? CHtml::encode($model->bugStatusFilter) : "open"), $bug_statuses);
                ?>
            </div>
        </div>
        <div class="span-19">
            <?php echo CHtml::textField('q', isset($model->filter) ? CHtml::encode($model->filter) : "", array('id' => 'text_filter')); ?>		
        </div>
        <div class="span-2 last">
            <?php echo CHtml::submitButton('Search', array('id' => 'btn_filter')); ?>
        </div>	
        <?php echo CHtml::endForm(); ?>
    </div>

    <!-- Advanced Search Form -->
    <div class="span-27 last" id="div_advanced_search" style="display:<?php echo $model->isAdvancedSearch ? 'inherit' : 'none' ?>">	
        <div class="wide form" id="form_advanced_search">
            <?php echo CHtml::beginForm('index', 'post'); ?>

            <h4>Advanced Search:</h4>
            <?php echo CHtml::errorSummary($model); ?>
            <div class="row">
                <?php echo CHtml::activeLabel($model, 'summary'); ?>
                <?php echo CHtml::activeTextField($model, 'summary', array('value' => $model->summary));
                ?>		
                <?php echo CHtml::error($model, 'summary'); ?>
            </div>	
            <div class="row">
                <?php echo CHtml::activeLabel($model, 'status'); ?>	
                <?php
                $statuses = Lookup::items('BugStatus');
                $statuses = array(-1 => '<any>') + $statuses;
                echo CHtml::dropDownList('Bug[status]', array('selected' => $model->status), $statuses);
                ?>
            </div>
            <div class="row">
                <?php echo CHtml::activeLabel($model, 'priority'); ?>
                <?php
                $items = Lookup::items('BugPriority');
                $items = array(-1 => '<any>') + $items;
                echo CHtml::activeDropDownList($model, 'priority', $items);
                ?>
                <?php echo CHtml::error($model, 'priority'); ?>
            </div>	
            <div class="row">
                <?php echo CHtml::activeLabel($model, 'date_created'); ?>	
                From:
                <?php
                $this->widget('zii.widgets.jui.CJuiDatePicker', array(
                    'name' => 'Bug[createdFrom]',
                    'value' => $model->createdFrom,
                    // additional javascript options for the date picker plugin
                    'options' => array(
                        'showAnim' => 'fold',
                    ),
                    'htmlOptions' => array(
                    //'style'=>'height:20px;'
                    ),
                ));
                ?>
                To:
                <?php
                $this->widget('zii.widgets.jui.CJuiDatePicker', array(
                    'name' => 'Bug[createdTo]',
                    'value' => $model->createdTo,
                    // additional javascript options for the date picker plugin
                    'options' => array(
                        'showAnim' => 'fold',
                    ),
                    'htmlOptions' => array(
                    //'style'=>'height:20px;'
                    ),
                ));
                ?>	
            </div>
            <div class="row">
                <?php echo CHtml::activeLabel($model, 'reported_by'); ?>
                <?php echo CHtml::activeTextField($model, 'reported_by', array('value' => $model->reported_by));
                ?>		
                <?php echo CHtml::error($model, 'reported_by'); ?>
            </div>	
            <div class="row">
                <?php echo CHtml::activeLabel($model, 'assigned_to'); ?>
                <?php echo CHtml::activeTextField($model, 'assigned_to', array('value' => $model->assigned_to));
                ?>		
                <?php echo CHtml::error($model, 'assigned_to'); ?>
            </div>	
            <div class="row buttons">
                <?php echo CHtml::submitButton('Search', array('id' => 'btn_filter')); ?>
            </div>

            <?php echo CHtml::endForm(); ?>
        </div>
    </div>

    <!-- Actions Toolbar -->
    <div class="span-27 last">
        <div class="div_actions">				
            <?php
            if (Yii::app()->user->checkAccess('pperm_manage_bugs', array('project_id'=>Yii::app()->user->getCurProjectId()))) {
                echo CHtml::link('Open New Bug', $this->createUrl('bug/create'));
            }
            ?>	
        </div>	
    </div>

            
    <div class="span-27 last">
        <?php
        $this->widget('zii.widgets.grid.CGridView', array(
            'dataProvider' => $dataProvider,
            'selectableRows' => null,
            'columns' => array(
                array(            
                    'class'=>'CCheckBoxColumn',			  			  
                    'id'=>'DeleteRows',
                    'selectableRows'=>2, // allow multiple rows to select
                ),    
                array(
                    'name' => 'id',
                    'type' => 'raw',
                    'value' => 'CHtml::link($data->id, \'view/\'.$data->id)',
                    'cssClassExpression' => '"column-right-align"',
                ),
                array(
                    'name' => 'status',
                    'value' => 'Lookup::item(\'BugStatus\', $data->status)',
                ),
                array(
                    'name' => 'priority',
                    'value' => 'Lookup::item(\'BugPriority\', $data->priority)',
                ),
                array(
                    'name' => 'date_created',
                    'value' => 'date("d/m/y H:i", $data->date_created)',
                ),
                array(
                    'name' => 'reported_by',
                    'value' => '$data->reporter->username',
                ),
                array(
                    'name' => 'assigned_to',
                    'value' => '$data->owner?$data->owner->username:""',
                ),
                array(
                    'header' => 'Repro',
                    'name' => 'reproducability',
                    'value' => 'Lookup::item(\'BugReproducability\', $data->reproducability)',
                ),
                array(
                    'name' => 'summary',
                    'type' => 'text',
                    'value' => 'MiscHelpers::addEllipsis($data->summary, 100)',
                ),
            ),
        ));
        ?>
    </div>

    <div class="span-27 last footnote">
        <?php
        $curVer = "";
        $totalFileSize = 0;
        $percentOfQuota = 0;
        $count = Yii::app()->user->getCurProject()->getBugAttachmentCount(
                $totalFileSize, $percentOfQuota);
        $totalFileSizeStr = MiscHelpers::fileSizeToStr($totalFileSize);
        $percentOfQuotaStr = sprintf("%.0f", $percentOfQuota);
        echo "This project contains total $totalFileSizeStr in $count bug file attachment(s)";
        if($percentOfQuota>=0)
            echo " ($percentOfQuotaStr% of disc quota).";
        ?> 	
    </div>

    <?php
    $script = <<<SCRIPT

$("#proj, #ver").bind('change', function(e)
{	
	$("#proj_form").submit();
});

$("#link_advanced_search").bind('click', function(e)
{	
	$("#div_simple_search").fadeToggle("fast");			
	$("#div_advanced_search").fadeToggle("fast");		
});
SCRIPT;

    Yii::app()->getClientScript()->registerScript(
            "Bug", $script, CClientScript::POS_READY);
    ?>


<?php endif; ?>